// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"urlshortener/ent/schema"
	"urlshortener/ent/url"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	urlMixin := schema.Url{}.Mixin()
	urlMixinFields0 := urlMixin[0].Fields()
	_ = urlMixinFields0
	urlFields := schema.Url{}.Fields()
	_ = urlFields
	// urlDescCreatedAt is the schema descriptor for created_at field.
	urlDescCreatedAt := urlMixinFields0[0].Descriptor()
	// url.DefaultCreatedAt holds the default value on creation for the created_at field.
	url.DefaultCreatedAt = urlDescCreatedAt.Default.(func() time.Time)
	// urlDescUpdatedAt is the schema descriptor for updated_at field.
	urlDescUpdatedAt := urlMixinFields0[1].Descriptor()
	// url.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	url.UpdateDefaultUpdatedAt = urlDescUpdatedAt.UpdateDefault.(func() time.Time)
}
